/* Rvencis Forge — js/certificate.js
   Builds a printable completion certificate for any course the learner has
   finished 100%. For signed-in members the completions come from the
   Supabase-backed Store, so the certificate can always be reprinted from any
   device; guests get a sign-in prompt because local progress can be lost.
   The credential ID is a deterministic hash of course + name + issue date —
   the issue date is the course's completion date (from the progress rows), so
   reprinting never changes the ID.
   Depends on: Data, UI, Store, SB. */
(function () {
  'use strict';

  var VERIFY_SALT = 'n8n-academy';

  /* Short deterministic id so two learners on the same course get different
     certificates, without any server round-trip. */
  function verifyId(courseSlug, name, when) {
    var input = VERIFY_SALT + '|' + courseSlug + '|' + name + '|' + when;
    var h = 5381;
    for (var i = 0; i < input.length; i++) h = ((h * 33) ^ input.charCodeAt(i)) >>> 0;
    var h2 = 52711;
    for (var j = input.length - 1; j >= 0; j--) h2 = ((h2 * 31) ^ input.charCodeAt(j)) >>> 0;
    return (h.toString(36) + h2.toString(36)).toUpperCase().slice(0, 10);
  }

  function completedCourses() {
    return Data.courses().filter(function (course) {
      var p = Store.courseProgress(course);
      return p.total > 0 && p.pct === 100;
    });
  }

  /* The course's completion day — its most recent lesson completion stamp
     (hydrated from the progress table for signed-in members). Feeding this
     stable date into verifyId() keeps reprints identical. */
  function completionDay(course, state) {
    var latest = 0;
    Data.flatten(course).forEach(function (e) {
      var ts = state.completed[course.slug + '/' + e.lesson.slug];
      if (ts && ts > latest) latest = ts;
    });
    return latest;
  }

  function fmtDate(d) {
    return d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
  }

  function certificateHtml(course, name, state, when) {
    var lessons = Data.flatten(course).length;
    var hours = Math.max(1, Math.round(Data.totalMinutes(course) / 60));
    var badgeCount = state.badges.length;
    var lvl = Store.levelFor(state.xp).level;

    return '<div class="cert" id="cert-print">' +
      '<div class="cert-inner">' +
        '<div class="cert-brand">' +
          '<img src="assets/logo.svg" width="34" height="34" alt="">' +
          '<span>Rvencis Forge</span>' +
        '</div>' +
        '<p class="cert-kicker">Certificate of completion</p>' +
        '<h2 class="cert-name">' + UI.esc(name) + '</h2>' +
        '<p class="cert-lead">has successfully completed every lesson of</p>' +
        '<h3 class="cert-course">' + UI.esc(course.title) + '</h3>' +
        '<p class="cert-meta">' + UI.esc(course.track ? Data.TRACK_META[course.track].label : 'n8n') +
          ' track · ' + lessons + ' lessons · about ' + hours + ' hour' + (hours === 1 ? '' : 's') + ' of hands-on practice</p>' +
        '<div class="cert-stats">' +
          '<div><b>' + state.xp + '</b><span>XP earned</span></div>' +
          '<div><b>' + lvl + '</b><span>Level</span></div>' +
          '<div><b>' + badgeCount + '</b><span>Badges</span></div>' +
        '</div>' +
        '<div class="cert-foot">' +
          '<div><span class="cert-label">Issued</span><b>' + UI.esc(when) + '</b></div>' +
          '<div><span class="cert-label">Credential ID</span><b>' + UI.esc(verifyId(course.slug, name, when)) + '</b></div>' +
          '<div><span class="cert-label">Verification</span><b title="Offline credential — the ID is derived from the course, graduate name and issue date.">Offline · ID-based</b></div>' +
        '</div>' +
      '</div>' +
    '</div>' +
    '<div class="cert-actions">' +
      '<button class="btn btn-primary" id="cert-print-btn">Print / Save as PDF</button>' +
      '<button class="btn btn-ghost" id="cert-copy">Copy credential ID</button>' +
    '</div>';
  }
  /* ---------- boot ---------- */
  document.addEventListener('DOMContentLoaded', function () {
    var select = document.getElementById('cert-course');
    var nameInput = document.getElementById('cert-name');
    var out = document.getElementById('cert-out');
    var goBtn = document.getElementById('cert-go');
    var all = Data.courses();
    /* course.html links here with ?course=<slug> — honor it. */
    var requested = new URLSearchParams(location.search).get('course');
    var requestedCourse = requested ? Data.getCourse(requested) : null;
    var lastOptions = '';
    var autoGenerated = false;

    function generate() {
      var course = Data.getCourse(select.value);
      if (!course) return;
      var state = Store.read();
      var p = Store.courseProgress(course);
      if (p.total === 0 || p.pct !== 100) {
        UI.toast('That course is not finished yet', 'danger');
        return;
      }
      var name = nameInput.value.trim() || 'Anonymous Builder';
      var day = completionDay(course, state);
      var when = fmtDate(new Date(day || Date.now()));
      out.innerHTML = certificateHtml(course, name, state, when);

      document.getElementById('cert-print-btn').addEventListener('click', function () { window.print(); });
      document.getElementById('cert-copy').addEventListener('click', function () {
        var id = out.querySelector('.cert-foot div:nth-child(2) b').textContent;
        if (navigator.clipboard) {
          navigator.clipboard.writeText(id).then(function () { UI.toast('Credential ID copied', 'success'); });
        } else {
          UI.toast('Credential ID: ' + id, 'info');
        }
      });
      out.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }

    function renderOptions(state) {
      var html = all.map(function (c) {
        var p = Store.courseProgress(c);
        var locked = !(p.total > 0 && p.pct === 100);
        return '<option value="' + c.slug + '"' + (locked ? ' disabled' : '') + '>' +
          UI.esc(c.title) + (locked ? ' — locked (' + p.pct + '%)' : ' — completed') + '</option>';
      }).join('');
      if (html === lastOptions) return;
      var keep = select.value;
      lastOptions = html;
      select.innerHTML = html;
      if (keep) select.value = keep;
    }

    function refresh() {
      var user = (window.SB && window.SB.user) || null;
      var state = Store.read();

      /* Guests: nothing saved to retrieve — invite them to sign in. */
      if (!user) {
        goBtn.disabled = true;
        out.innerHTML = '<div class="callout callout-info">' + UI.icon('lock', 18) +
          '<div><strong>Sign in to save and retrieve your certificate permanently.</strong> ' +
          'Right now your progress lives only in this browser — finish a course and it unlocks here, ' +
          'but a cleared cache would take the certificate with it. ' +
          '<a class="btn btn-primary btn-sm" href="auth.html?next=certificate.html">Sign in</a></div></div>';
        return;
      }

      if (state.user && state.user.name && !nameInput.value) nameInput.value = state.user.name;

      renderOptions(state);
      var done = completedCourses();

      if (!done.length) {
        var focus = requestedCourse || all[0];
        out.innerHTML = '<div class="callout callout-info">' + UI.icon('doc', 18) +
          '<div>Finish every lesson in a course and it unlocks here. ' +
          (focus
            ? '<strong>' + UI.esc(focus.title) + '</strong> is at <strong>' + Store.courseProgress(focus).pct + '%</strong> — keep going.'
            : 'No courses published yet.') + '</div></div>';
        if (requestedCourse) select.value = requestedCourse.slug;
        goBtn.disabled = true;
        return;
      }

      select.value = (requestedCourse && done.some(function (c) { return c.slug === requestedCourse.slug; }))
        ? requestedCourse.slug : done[0].slug;
      goBtn.disabled = false;
      if (!autoGenerated) {
        autoGenerated = true;
        generate();
      }
    }

    goBtn.addEventListener('click', generate);
    select.addEventListener('change', generate);
    refresh();
    Store.on(refresh);
  });
})();